import React from 'react';
import PageTitle from '../PageTitle/PageTitle';
import './Blog.css'

const Blog = () => {
    return (
        <div className="qna-container min-vh-100">
            <PageTitle title='Blogs'/>
            <h1>Difference between Javascript and Node JS :</h1>
            <p className="fw-bold">Javascript:</p>
            <p>
                JavaScript is mainly a web-based platform where you can write codes for both the client and server sides.It does not need a dedicated server.<br />Javascript is used in frontend development.JavaScript can support HTML languages.This is used for developing websites, server apps, wearable apps and more.
            </p>
            <p className="fw-bold">Node JS :</p>
            <p>
                Node.JS is based on JavaScript and allows the Node.Js developers to run codes on the servers beyond the web browsers.<br />It needs dedicated servers to perform.Nodejs is used in server-side development.NodeJS usually support single-thread JS language.<br />This is used for creating cross-platform and server-based applications.
            </p>


            <h1> When should you use nodejs and when should you use mongodb :</h1>
            <p>
                Node.js is an open source server environment which uses JavaScript on the server to develop backend applications.
            </p>

            <h1>Differences between SQL and NoSQL databases. :</h1>
            <p className="fw-bold">SQL:</p>
            <p>
                SQL is a relational database.Data is present in the form of tables, rows, and columns.Fixed schema design & structure.<br /> Possible to perform the complex queries.It follows the ACID(Atomicity, Consistency, Isolation, Durability) property.
            </p>
            <p className="fw-bold">NoSQL :</p>
            <p>
                NoSQL is a non-relational database.Data is present in the form of collections and documents.<br />Dynamic schema design and structure.Not possible to perform complex queries.<br />It follows the CAP(Consistency, Availability, Partition tolerance) principle.
            </p>

            <h1> What is the purpose of jwt and how does it work :</h1>
            <p>
                In short, JWTs are used as a secure way to authenticate users and share information. <br />

                JSON Web Token is an open standard used to share security information between two parties a client and a server.<br />Usually, the token is generated by a server and sent to the client. It is signed by one party's private key, <br /> so that both parties are able to verify that the token is legitimate. And both parties are able to read its content.<br /> JWTs are an excellent fit for REST API authentication.
                <br /> <br />
                A JWT is a Base64URL encoded string, split into three sections, delimited by periods.
                <br />
                <span className='fw-bold'>Section 01- header</span>: This section contains JWT metadata, typically information about the type of token and the algorithm used to sign it. It is encoded JSON. <br />
                 <span className='fw-bold'>Section 02- payload</span>. This is the content of the token and is also encoded JSON. <br />
                 <span className='fw-bold'>Section 03- signature</span>. This is the SHA256 (or some other HMAC) hash of the encoded header, encoded payload, and a secret.<br /> This part of the JWT is used to verify the integrity of the message.

            </p>
        </div>
    );
};

export default Blog;